# Generated by Django 3.2.9 on 2021-12-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
