# Generated by Django 3.2.9 on 2021-12-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_login', '0003_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
