# Generated by Django 3.2.9 on 2022-01-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_login', '0005_auto_20220122_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mobile_checked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
