# Generated by Django 3.2.9 on 2021-12-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211231_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
