# Generated by Django 3.2.9 on 2022-01-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220109_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
