# Generated by Django 3.2.9 on 2021-12-31 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
                ('shortdesc', models.CharField(blank=True, max_length=255, null=True, verbose_name='short description')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('f', 'Feature'), ('i', 'Infographic'), ('g', 'Gallery')], max_length=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('tag', models.ManyToManyField(to='grups.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
                ('shortdesc', models.CharField(blank=True, max_length=255, null=True, verbose_name='short description')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PUB', 'publish'), ('DRF', 'draft'), ('DEL', 'delete'), ('NOT', 'notset')], max_length=3)),
                ('category', models.ManyToManyField(to='grups.Category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('tag', models.ManyToManyField(to='grups.Tag')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='FeatureStory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.story',),
        ),
        migrations.CreateModel(
            name='GalleryStory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.story',),
        ),
        migrations.CreateModel(
            name='InfographicStory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.story',),
        ),
    ]
