# Generated by Django 3.2.9 on 2022-01-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0002_type'),
        ('post', '0002_auto_20220108_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='grups.Tag'),
        ),
        migrations.AlterField(
            model_name='story',
            name='tag',
            field=models.ManyToManyField(blank=True, to='grups.Tag'),
        ),
    ]
