# Generated by Django 3.2.9 on 2022-01-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
