# Generated by Django 3.2.9 on 2022-01-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='status',
            field=models.CharField(blank=True, choices=[('done', 'Fully completed'), ('load', 'in progress'), ('canc', 'canceled')], max_length=4, null=True),
        ),
    ]
