# Generated by Django 3.2.9 on 2022-01-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_basketitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='Chekedout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
