# Generated by Django 3.2.9 on 2022-01-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20220106_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_products_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
