# Generated by Django 3.2.9 on 2022-01-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_basket_total_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
