# Generated by Django 3.2.9 on 2022-01-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shop_type'),
        ('basket', '0007_basketitem_desc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'product')},
        ),
    ]
