# Generated by Django 3.2.9 on 2021-12-31 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('chek', 'verified'), ('load', 'in progress'), ('rejc', 'rejected'), ('dele', 'deleted')], max_length=4, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('desc', models.TextField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('Address', models.TextField(blank=True, null=True)),
                ('contact_number', models.TextField(blank=True, null=True)),
                ('admin_description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='grups.Category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('body', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=300)),
                ('weight', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('shippment', models.CharField(choices=[('pey', 'peyk_motori'), ('pos', 'post'), ('dgp', 'digikala_post')], max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('category', models.ManyToManyField(to='grups.Category')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shop')),
                ('tag', models.ManyToManyField(to='grups.Tag')),
            ],
            options={
                'unique_together': {('shop', 'name')},
            },
        ),
    ]
