# Generated by Django 3.2.9 on 2022-01-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0001_initial'),
        ('products', '0002_alter_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='grups.Category'),
        ),
    ]
