# Generated by Django 3.2.9 on 2022-01-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grups', '0002_type'),
        ('products', '0005_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, to='grups.Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(blank=True, to='grups.Category'),
        ),
    ]
